# Configuration file for Prettier

printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: 'all'
bracketSpacing: false
arrowParens: 'always'
proseWrap: 'preserve'
endOfLine: 'lf'
singleAttributePerLine: true

overrides:
- files: '*.css'
  options:
    printWidth: 120
